version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    links:
      - fpm
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/laravel-docker
  fpm:
    build:
      context: .
      dockerfile: docker/fpm.dockerfile
    links:
      - mysql
    volumes:
      - ./:/var/www/laravel-docker
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    image: mysql:5.7
    ports:
      - 3307:3307
